### ISSUE TITLE
Crash on minecraft Forge Launch (Before Loading window pop up)

### ISSUE THREAD

**Issue by VirtualGaming1** [lukas2005s-Team/Device-Mod-Apps#13]
When i press launch on the launcher it close (That what it should do) and then pop back open saying it have crashed.

[22:28:59] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[22:28:59] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[22:28:59] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[22:28:59] [main/INFO]: Forge Mod Loader version 14.23.4.2709 for Minecraft 1.12.2 loading
[22:28:59] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Users\John Hanzely\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25
[22:28:59] [main/ERROR]: Contained Dep is not in the jar: mp3spi1.9.5.jar
[22:28:59] [main/ERROR]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at C:\Users\John Hanzely\Documents\Curse\Minecraft\Instances\Real Life Modpack 1.12.2 (Public Update branch) for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:109) ~[forge-1.12.2-14.23.4.2709.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79) ~[forge-1.12.2-14.23.4.2709.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.4.2709.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:139) ~[forge-1.12.2-14.23.4.2709.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalStateException: Invalid contained dep, Missing from jar: mp3spi1.9.5.jar
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.extractPacked(LibraryManager.java:247) ~[forge-1.12.2-14.23.4.2709.jar:?]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.extractPacked(LibraryManager.java:199) ~[forge-1.12.2-14.23.4.2709.jar:?]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.cleanDirectory(LibraryManager.java:165) ~[forge-1.12.2-14.23.4.2709.jar:?]
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.setup(LibraryManager.java:96) ~[forge-1.12.2-14.23.4.2709.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:104) ~[forge-1.12.2-14.23.4.2709.jar:?]
	... 5 more
[22:28:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[22:28:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[22:28:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[22:28:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[22:28:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:968)
[22:28:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[22:28:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by lukas2005** [comment]
i'm right now away from home so i'm unable to look / respond to crash logs and issues. I'll be back in about 2 days

**Comment by lukas2005** [comment]
I uploaded a new release (0.1.6) to curse. It it won't work reopen the issue.
